### ISSUE TITLE
Docker 镜像下载失败

### ISSUE THREAD

**Issue by HuanKongzzz** [Slontia/lgtbot-mirai#1]
执行 docker pull slontia/mirai-mcl-http:latest slontia/lgtbot-mirai:latest报错
![Screenshot_20221202-173521~2](https://user-images.githubusercontent.com/119497994/205263024-b3b4b245-1932-4bbd-81a4-50937c1903b0.png)

**Comment by Slontia** [comment]
如果拆成两条指令执行，会有类似问题吗？

```
docker pull slontia/mirai-mcl-http:latest
docker pull slontia/lgtbot-mirai:latest
```

**Comment by HuanKongzzz** [comment]
没有语法错误了，但是连接错误，求解决
![Screenshot_20221202-183741~2](https://user-images.githubusercontent.com/119497994/205274345-c5dabb15-6f03-4b5a-8978-0255f64c54a8.png)

**Comment by Slontia** [comment]
`docker ps` 执行会报错吗

**Comment by HuanKongzzz** [comment]
有的
![Screenshot_20221202-184942~2](https://user-images.githubusercontent.com/119497994/205276418-af07a6a1-da09-47cf-9027-4df4a2c377ff.png)

**Comment by Slontia** [comment]
https://blog.csdn.net/pangdongh/article/details/80203103
找到篇文章，参考下看看能不能解决呢

**Comment by HuanKongzzz** [comment]
用的不是win10系统，没有找到那个界面，kitematic一直加载中打不开
![Screenshot_20221202-191458](https://user-images.githubusercontent.com/119497994/205280590-d3b843c2-2b63-4c12-8e3e-5e2eb661634d.png)

**Comment by HuanKongzzz** [comment]
找到了相应问题的解决文章，麻烦了

**Comment by Slontia** [comment]
> 找到了相应问题的解决文章，麻烦了

好的，不客气
